### ISSUE TITLE
When i'm calling {id} I get -1

### ISSUE THREAD

**Issue by ghost** [Azuriom/AzLink-FiveM#1]
Hello, I have recently installed your cms .

But there is a big issues with AzLink because when you call {id} to get the ID of the player it return -1

So we can't give anything to the players with the issues

![image](https://github.com/Azuriom/AzLink-FiveM/assets/2059913/fc41a155-52a1-42cb-901c-f1c5a652c533)

giveitem {id} water_bottle 1

**Comment by MrMicky-FR** [comment]
The player must be online to use `{id}` and `{fivem_id}`. The other variables can be used both online or offline

**Comment by ghost** [comment]
Salut, merci d'avoir répondu je vois que tu es français cela va être plus facile pour discuter.

J'était bien en ligne lorsque j'ai fais tout mes test
